### ISSUE TITLE
Play/Pause button acts strange after respring 

### ISSUE THREAD

**Issue by wonkieinc** [Nosskirneh/RoadRunner-Public#1]
After respringing, Play/Pause on lockscreen doesn’t function or display correctly. Pausing music pauses successfully, though the icon switches back to showing the pause button again as if the media was playing

**Comment by john-crane-69** [comment]
i noticed that too, seems like a lag issue which kinda fixes it self if you give it a couple of seconds or pause from the music app itself

**Comment by Nosskirneh** [comment]
Is this happening on the stock iOS music player or are you using some other tweak for the widget? Please disable all other tweaks to find out.

**Comment by Nosskirneh** [comment]
I've heard some reports of this on the Discord server saying it happens with Prism and has nothing to do with RoadRunner, so I'm closing this one. Feel free to reopen it if I'm mistaken though.
