### ISSUE TITLE
Settings.app stuck at launching screen until a respring

### ISSUE THREAD

**Issue by yur1xpp** [Nosskirneh/RoadRunner-Public#12]
This bug was probably fixed in latest update, but I still experiencing this issue with Settings.app (didn't happens on Spotify anymore though). This issue happens occasional, so it's quite hard to reproduce. However, since I have disabled RoadRunner (did an userspace reboot to unhook any deamon injection) for a week now, and this issue doesn't happens during that time period. Awesome tweak btw!

**Comment by Nosskirneh** [comment]
Thanks for reporting! Sounds like a conflicting tweak. If you disable everything else, does it still happen? I know it might be difficult testing that if it only happens occasionally, but knowing how to reproduce it is the only way to fix it.

**Comment by yur1xpp** [comment]
Yeah totally understandable. But I can't live without all other tweaks for a week XD
I'll get back to you once I decided to do so, but not going to be very soon.
