### ISSUE TITLE
Causes respiring when I open Cydia

### ISSUE THREAD

**Issue by finnessedyou** [Nosskirneh/RoadRunner-Public#16]
When I open cydia it causes a respiring and on the third respiring it finally opens. But whenever I respiring again it will start the 3 respiring cycle again. I have CrashReporter and it says that it may be caused by CallbarX, substitute-loader dylib, or substitute-ingerter.dylib. I’m not sure tho. I’m on IOS 13.5 IPhone 8 Plus.

**Comment by Nosskirneh** [comment]
I don’t recommend excluding termination for package managers. If previously installed a package that required respring, Cydia will respring once more when you open it again. Now, I’m not going to make certain apps non-excludable, that’s entirely up for the user to decide which apps work and which do not. Most apps work, some don’t.

If I misunderstood this issue, feel free to reopen it.
