### ISSUE TITLE
postinst and postrm scripts are broken

### ISSUE THREAD

**Issue by hopolapopola** [Nosskirneh/RoadRunner-Public#18]
When using the latest dpkg from procursus, they fail with `Exec format error` because they lack shebangs on the first line. It's a simple fix
![image](https://user-images.githubusercontent.com/8025839/116971146-7a635b80-acfc-11eb-8b72-afbe601ad02d.png)

**Comment by Nosskirneh** [comment]
First off, sorry for the late reply. I've fixed this until the next release. Thanks for reporting!
