### ISSUE TITLE
Audio pauses after respring

### ISSUE THREAD

**Issue by bbareta** [Nosskirneh/RoadRunner-Public#19]
I had to recently re-install all my tweaks and I had no recollection of this happening before. In all media apps (Music, Spotify, Youtube), RoadRunner will work through the respring, but after my lockscreen shows up again, the audio suddenly pauses itself after 2-3 seconds. I tried respringing through different methods, like with Activator, CC module, a tweak called Dragspring, and I get the same problem every time. I'm on iOS 13.5 on unc0ver.

Edit: I tried disabling my tweaks one at a time and found out it's a conflict with Voice Changer XS.

**Comment by Nosskirneh** [comment]
In the past, PauseOnMute has been known to cause this. There are probably other tweaks that does this as well. Use iCleaner Pro and disable tweaks until you find out which it is.

Kind regards,
Andreas

**Comment by bbareta** [comment]
Hey, it was a conflict with VoiceChanger XS!
