### ISSUE TITLE
Conflict with SpringArtwork

### ISSUE THREAD

**Issue by bbareta** [Nosskirneh/RoadRunner-Public#2]
I have SpringArtwork installed and enabled only on the Homescreen and not on the Lockscreen, I just did a quick test and whenever I respring, SpringArtwork becomes active on the Lockscreen.

It goes away when I unlock the device for the first time and go back to the Lockscreen though. I did my tests with Spotify if it matters knowing that.

**Comment by Nosskirneh** [comment]
Thanks for reporting! I get the same thing, I'll try to see why that could happen.

**Comment by bbareta** [comment]
No problem, thank you for replying and being an awesome dev!

**Comment by Nosskirneh** [comment]
Thanks for the kind words!

Sorry about the delay, other things got in the way. beta13 of SpringArtwork fixes this.

**Comment by bbareta** [comment]
Thank you for fixing it!
