### ISSUE TITLE
Roadrunner and switchus Conflict

### ISSUE THREAD

**Issue by john-crane-69** [Nosskirneh/RoadRunner-Public#4]
i already texted this to you on twitter but just in case ill post it here

There is a conflict between roadrunner and switchus where when you try to close all apps it boots you to safemode
When using killbackground13 instead it doesn't boot you to safemode

**Comment by thefamousunkown** [comment]
Same. Bought it last night but it conflicts with Switchus. Gump actually worked just fine for me I just didn’t like their privacy policy. It would be nice to have this conflict fixed so I can use the tweak :)

**Comment by john-crane-69** [comment]
> Same. Bought it last night but it conflicts with Switchus. Gump actually worked just fine for me I just didn’t like their privacy policy. It would be nice to have this conflict fixed so I can use the tweak :)

i bypassed this issue with two things
lynx and killall pro
with lynx i got the switchus grid style app switcher and with killall pro i got the kill apps feature
so far no issues and  It’s a great workaround

**Comment by thefamousunkown** [comment]
I don’t think it’s a good work around when you’re forced to used two tweaks for the function of one. Specially when the one (swithchus) is paid. Will have to wait for an update or going back to gump.

--
Rafael

On Apr 29, 2020, at 3:02 AM, Wishy <notifications@github.com> wrote:

﻿

Same. Bought it last night but it conflicts with Switchus. Gump actually worked just fine for me I just didn’t like their privacy policy. It would be nice to have this conflict fixed so I can use the tweak :)

i bypassed this issue with two things
lynx and killall pro
with lynx i got the switchus grid style app switcher and with killall pro i got the kill apps feature
so far no issues and It’s a great workaround

**Comment by Nosskirneh** [comment]
I've changed some things to make it work better with Switchus and other app switcher tweaks (such as Gesto). I have some other issues to fix before pushing a new version, but it's being worked on at least.
Thanks for reporting btw!

**Comment by thefamousunkown** [comment]
Thanks!!! I’m sure it will come out great. Looking forward to it.

--
Rafael

On Apr 29, 2020, at 11:35 AM, Andreas Henriksson <notifications@github.com> wrote:

﻿

I've changed some things to make it work better with Switchus and other app switcher tweaks (such as Gesto). I have some other issues to fix before pushing a new version, but it's being worked on at least.
Thanks for reporting btw!

**Comment by Nosskirneh** [comment]
beta2 should fix this. Thanks for reporting!
