### ISSUE TITLE
[Bug] Flow slide skip gets disabled

### ISSUE THREAD

**Issue by john-crane-69** [Nosskirneh/RoadRunner-Public#5]
![F5353EB2-24C9-42CA-8A28-4D19461F8C9F](https://user-images.githubusercontent.com/15282798/78994270-4c870400-7b48-11ea-97c7-cc3a58b90b45.png)
so when you respring and roadrunner is on them music keeps playing as it should but after that flow gets kinda broken
what happens is that you can only skip with the skip buttons and not slide with your finger
and you cannot see the artwork of the previous and the upcoming song ( only the current one) as shown in the picture provided

**Comment by Nosskirneh** [comment]
This is a known issue. Muirey (dev of Flow) is working on this as far as I know.

**Comment by john-crane-69** [comment]
ok ill wait for Muirey’s update
its not a major issue so I’m ok to wait regardless

**Comment by Nosskirneh** [comment]
Hopefully he'll be able to solve it. Thanks for opening an issue nevertheless! ☺️

**Comment by Nosskirneh** [comment]
Just a heads up that this works now by using the latest version of RoadRunner and Flow :)
