### ISSUE TITLE
Bluetooth Headphone Support

### ISSUE THREAD

**Issue by samaero** [Nosskirneh/RoadRunner-Public#7]
Roadrunner doesn’t work with my Bluetooth device - is this a bug or intended feature? Love the tweak idea but I use Bluetooth 99% of the time.

**Comment by Nosskirneh** [comment]
Hi! Sorry about the delay! It works with my Bluetooth headset, what kind of device do you use? Also, just to make sure, have you tried without all other tweaks?

**Comment by samaero** [comment]
Hey - sorry, I should have come back and let you know it's not an
issue anymore! I think it just needed a couple of resprings before it
caught. Thank you!
