### ISSUE TITLE
Super Recorder X+ 

### ISSUE THREAD

**Issue by aakashkk-zz** [Nosskirneh/RoadRunner-Public#8]
Tweak doesn’t work with Super Recorder X+!

I tracked this by disabling all tweaks via iCleaner and testing until I found the cause!

**Comment by Nosskirneh** [comment]
Thanks for reporting! I have yet to receive a response from its dev.

**Comment by aakashkk-zz** [comment]
Hi @Nosskirneh 

I updated super recorder x+ to the the latest! Released today (06-04-2020) Ver. 3.17 on the hacx repo (https://hacx.org/repo/) and the issue is resolved! 

So I’ll go ahead and close this one!

**Comment by Nosskirneh** [comment]
Perfect! Do you mind testing NextUp 2 as well? I’ve seen reports of the same happening for that.

**Comment by aakashkk-zz** [comment]
Hi Andreas,

Sure! I installed it and am using the trail currently. 

I have Ver. 1.3.4-1 of next up 2, roadrunner 1.0 beta 2, and super recorder x+ 3.17-2.

Nextup 2 worked perfectly as well with Spotify and Apple Music!

**Comment by Nosskirneh** [comment]
Perfect! Thanks for testing!
